# -*- coding: utf-8 -*-
"""Correlación.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V6r3ZaIrztgK6RQ1ZifEtAe-aNvnaX_s
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr

spark = SparkSession.builder.appName("Notas de estudiantes").getOrCreate()

spark

data = [("Alex", 20), ("Luisa", 18), ("Carlos", 15), ("Lucas", 14), ("Sara", 18),("Aron", 16),("Camila", 13),("Susana", 19),("Alfredo", 5),("Alonso", 11),("Karen", 9),("Alexa", 8),("Hellen", 2),("Mauricio", 6),("Luciana", 12),("Jacob", 18),("Estefani", 19),("Daniela", 17)]
columns = ["Nombre", "Notas"]
variable = spark.createDataFrame(data, columns)

data_var = [(3,4), (4,3), (3,4), (2,5), (5,4), (5,3), (5,4), (2,3), (2,2), (5,5), (1,4), (4,2), (2,4), (4,5), (5,4)]
columns_var = ["var1", "var2"]
variable_corr = spark.createDataFrame(data_var, columns_var)

correlacion = variable_corr.select(corr(col("var1"), col("var2")).alias("correlacion")).collect()[0]["correlacion"]

print ("La correlacion es:", correlacion)